INSERT INTO USERS (USER_ID,USERNAME, EMAIL, COUNTRY, HOME_ADDRESS, PEDIDO_ID, PASSWORD) VALUES (0,'user1', 'mencia@hotmail.com', 'Spain', 'Calle mirador 8', 1, '{noop}qwerty123');
INSERT INTO USERS (USER_ID,USERNAME, EMAIL, COUNTRY, HOME_ADDRESS, PEDIDO_ID, PASSWORD) VALUES (1,'user2', 'lola@hotmail.com', 'Spain', 'Calle Duque 10', 0, '{bcrypt}qwerty456');


INSERT INTO ELEMENTO (FOOD_ID,FOOD_NAME,PRICE,INGREDIENTES,KALORIES) VALUES (0,'Hamburguesa de pollo',3.74,'pan, pollo lechuga',100);
INSERT INTO ELEMENTO (FOOD_ID,FOOD_NAME,PRICE,INGREDIENTES,KALORIES) VALUES (1,'patatas',2.0,'patatas',200);

INSERT INTO PEDIDO(PEDIDO_ID,PEDIDO_NAME,FOOD_ID,PRICE_PEDIDO) VALUES (0,'Mencia', 0 ,6.74);
INSERT INTO PEDIDO(PEDIDO_ID,PEDIDO_NAME, FOOD_ID,PRICE_PEDIDO) VALUES (1,'Lola', 1,2.0);




INSERT INTO PAGAR (CARD_NUMBER, CARD_NAME, USER_ID, PRICE_PEDIDO) VALUES (100, 'Mencia', 0, 10);
INSERT INTO PAGAR (CARD_NUMBER, CARD_NAME, USER_ID, PRICE_PEDIDO) VALUES (200, 'Lola',1, 15);

INSERT INTO DISCOUNT (DISCOUNT_ID, PRICE_DISCOUNT, USER_ID) VALUES (0,8,0);
INSERT INTO DISCOUNT (DISCOUNT_ID, PRICE_DISCOUNT, USER_ID) VALUES (1,8,0);
INSERT INTO DISCOUNT (DISCOUNT_ID, PRICE_DISCOUNT, USER_ID) VALUES (2,5,1);