DROP TABLE IF EXISTS USERS;

CREATE TABLE  "USERS" (
    "USER_ID" IDENTITY NOT NULL PRIMARY KEY,
	"USERNAME" VARCHAR2(40) NOT NULL,
	"EMAIL" VARCHAR2(35) NOT NULL,
	"COUNTRY" VARCHAR2(20) NOT NULL,
    "HOME_ADDRESS" VARCHAR(30) NOT NULL,
	"PEDIDO_ID" NUMBER NOT NULL,
    "PASSWORD" VARCHAR2(512) NOT NULL
);


DROP TABLE IF EXISTS ELEMENTO;

CREATE TABLE  ELEMENTO (
	FOOD_ID IDENTITY NOT NULL PRIMARY KEY,
    FOOD_NAME VARCHAR2(20) NOT NULL ,
	PRICE FLOAT NOT NULL,
	INGREDIENTES VARCHAR2(100) NOT NULL,
	KALORIES NUMBER NOT NULL
);



DROP TABLE IF EXISTS PEDIDO;

CREATE TABLE  PEDIDO (
	PEDIDO_ID IDENTITY NOT NULL PRIMARY KEY,
	PEDIDO_NAME VARCHAR2(20) NOT NULL,
    FOOD_ID NUMBER NOT NULL,
	PRICE_PEDIDO FLOAT NOT NULL
);

DROP TABLE IF EXISTS PAGAR;

CREATE TABLE PAGAR(
	CARD_NUMBER IDENTITY NOT NULL PRIMARY KEY,
	CARD_NAME VARCHAR(45) NOT NULL,
    USER_ID NUMBER NOT NULL,
	PRICE_PEDIDO FLOAT NOT NULL
);

DROP TABLE IF EXISTS DISCOUNT;

CREATE TABLE DISCOUNT(
    DISCOUNT_ID IDENTITY NOT NULL PRIMARY KEY,
	PRICE_DISCOUNT FLOAT NOT NULL,
	USER_ID NUMBER NOT NULL
)